// User types

export const HAS_USER = "HAS_USER";
export const SHOW_MESSAGE_FOR = "SHOW_MESSAGE_FOR";
export const USER_LOGIN = "USER_LOGIN";
export const USER_LOGOUT = "USER_LOGOUT";

// Navigation types

export const SET_CURRENT_STEP = "SET_CURRENT_STEP";

// Foods types

export const ADD_ITEMS = "ADD_ITEMS";
export const CHANGE_QUANTITY_ITEMS = "CHANGE_QUANTITY_ITEMS";
export const DELETE_ITEMS = "DELETE_ITEMS";
export const FOOD_FILTERED = "FOOD_FILTERED";
export const CHANGE_TOTAL_AMOUNT = "CHANGE_TOTAL_AMOUNT";

// Location types

export const ADD_LOCATION = "ADD_LOCATION";
export const SET_DEFAULT_LOCATION = "SET_DEFAULT_LOCATION";
export const MODIFY_LOCATION = "MODIFY_LOCATION";
export const SET_DELIVERY_INSTRUCTIONS = "SET_DELIVERY_INSTRUCTIONS";
export const SET_DELIVERY_TYPE = "SET_DELIVERY_TYPE";

// Cart types

export const ADD_SPECIAL_NOTES = "ADD_SPECIAL_NOTES";
export const CLEAR_CART = "CLEAR_CART";
export const SET_DISCOUNT = "SET_DISCOUNT";

// Payment types

export const SET_PAYMENT_INFORMATION = "SET_PAYMENT_INFORMATION";
export const CHECK_PAYMENT_INFORMATION_COMPLETE =
  "CHECK_PAYMENT_INFORMATION_COMPLETE";
